#!/bin/bash

##################################################
# Reflector:  Refresh Mirrorlist
# ##################################################
# paru -S reflector
# sudo reflector --verbose --country 'Germany' -l 15 -p https --sort rate --save /etc/pacman.d/mirrorlist

##################################################
# Touchpad Gestures
##################################################
# https://github.com/bulletmark/libinput-gestures

# paru -S gestures libinput-gestures xorg-xinput
# sudo gpasswd -a $USER input
# libinput-gestures-setup autostart start

# ~/.config/libinput-gestures.conf gestures for Google Chrome
# gesture swipe up        4       xdotool key control+plus
# gesture swipe down      4       xdotool key control+minus
# gesture swipe left      4       xdotool key alt+Right
# gesture swipe right     4       xdotool key alt+Left
# gesture swipe right_up  4       xdotool key control+Tab
# gesture swipe left_up   4       xdotool key control+shift+Tab
# gesture swipe left_down 4       xdotool key control+w
# gesture swipe right_down 4      xdotool key control+shift+t

install() {

    ECOS_INITIALIZED="$HOME/.ecos/.workspace/initialized"

    exec_paru() {
        paru --noconfirm --needed --sudoloop -S $1
    }

    ##################################################
    # INSTALL PACKAGES
    ##################################################
    paru -Syyu

    # Gnome Minimal -  https://archlinux.org/groups/x86_64/gnome/
    exec_paru "gdm gnome-shell gnome-control-center gnome-terminal nautilus xdg-user-dirs"

    # Gnome Shell Extensions
    exec_paru "chrome-gnome-shell-git"
    exec_paru "gnome-shell-extensions"
    exec_paru "gnome-shell-extension-blur-my-shell-git"
    exec_paru "gnome-shell-extension-x11gestures"

    # ZSH
    exec_paru "zsh-autosuggestions zsh-syntax-highlighting"

    # Mouse Gestures
    exec_paru "touchegg touche"

    # System Tools
    exec_paru "gnome-keyring seahorse"
    exec_paru "gnome-tweak-tool"
    exec_paru "evince eog gthumb gedit gnome-calculator totem"
    exec_paru "gnome-disk-utility gnome-usage neofetch htop"
    exec_paru "gnome-screenshot"
    exec_paru "gnome-backgrounds"
    exec_paru "pacman-contrib man-db"
    exec_paru "hunspell hunspell-en_us hunspell-de"
    exec_paru "samba"
    exec_paru "gvfs gvfs-mtp gvfs-smb gvfs-nfs"
    exec_paru "gnome-user-share nfs-utils"
    exec_paru "wireless_tools wmctrl xdotool"
    exec_paru "zenity ffmpeg youtube-dl rsync curl"
    exec_paru "pavucontrol"
    exec_paru "cava"
    exec_paru "cups"

    # Codecs
    exec_paru "gst-libav"

    # Archive Manager
    exec_paru "file-roller zip unzip unrar"

    # Apps
    exec_paru "firefox"
    exec_paru "gnome-calendar"
    exec_paru "gnome-weather"
    exec_paru "rhythmbox-plugin-alternative-toolbar-git"
    exec_paru "geary"
    exec_paru "keepassxc"
    exec_paru "libreoffice-still-de"

    # Fonts
    exec_paru "ttf-dejavu"
    exec_paru "ttf-liberation"
    exec_paru "noto-fonts-emoji"
    exec_paru "lib32-fontconfig"

    # Icons
    exec_paru "qogir-icon-theme-git"

    # Vim
    exec_paru "vim"

    # Wine & Dependencies
    exec_paru "wine-staging lutris-wine-meta winetricks"

    # Hide mouse pointer
    #exec_paru "unclutter"

    # VSCodium
    #exec_paru "vscodium-bin vscodium-bin-marketplace"

    # Spotify
    #curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | gpg --import -
    #exec_paru "spotify-adblock-git"

    # Kodi
    #exec_paru "kodi-x11 kodi-addon-inputstream-adaptive"

    # VirtualBox
    #exec_paru "virtualbox virtualbox-host-modules-arch"

    # Lutris
    # Wine: https://github.com/lutris/docs/blob/master/WineDependencies.md
    # Graphic Driver: https://github.com/lutris/docs/blob/master/InstallingDrivers.md
    #exec_paru "lutris lutris-wine-meta"

    ##################################################
    # CONFIGURATION
    ##################################################

    # GNOME DISPLAY MANAGER
    local gdm_config_file="/etc/gdm/custom.conf"

    # GNOME: Enable X11 instead of Wayland
    sudo sed -i "s/^#WaylandEnable=false/WaylandEnable=false/g" "$gdm_config_file"

    # GNOME AUTO LOGIN
    if ! grep -qrnw "$gdm_config_file" -e "AutomaticLoginEnable=True"; then
        sudo sed -i "s/^WaylandEnable=false/WaylandEnable=false\n\nAutomaticLoginEnable=True\nAutomaticLogin=$USER/g" "$gdm_config_file"
    fi

    # SAMBA CONFIG
    if [ ! -f "/etc/samba/smb.conf" ]; then
        {
            echo "[global]"
            echo "   workgroup = WORKGROUP"
            echo "   log file = /var/log/samba/%m"
        } >"/tmp/smb.conf"
        sudo mv "/tmp/smb.conf" "/etc/samba/smb.conf"
    fi

    # TLP CONFIG
    if [ -f "/etc/tlp.conf" ]; then
        sudo sed -i "s/^#CPU_BOOST_ON_AC=1/CPU_BOOST_ON_AC=0/g" "/etc/tlp.conf"
        sudo sed -i "s/^#CPU_BOOST_ON_BAT=0/CPU_BOOST_ON_BAT=0/g" "/etc/tlp.conf"
    fi

    # ENABE SERVICES
    sudo systemctl enable gdm.service
    sudo systemctl enable smb.service
    sudo systemctl enable nmb.service
    sudo systemctl enable touchegg.service
    sudo systemctl enable avahi-daemon
    sudo systemctl enable bluetooth.service
    sudo systemctl enable cups.service

    # ECOS TWEAKS
    $ECOS_CORE --tweak install theme_whitesur
    $ECOS_CORE --tweak install gnome-extension-arch_update_indicator
    $ECOS_CORE --tweak install gnome-extension-dash_to_panel
    $ECOS_CORE --tweak install gnome-extension-just_perfection
    $ECOS_CORE --tweak install gnome-extension-tray_icons_reloaded

    # SET GNOME SETTINGS
    gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:appmenu'
    gsettings set org.gnome.mutter center-new-windows true

    # SET THEMING
    if [ ! -f "$ECOS_INITIALIZED" ]; then
        gsettings set org.gnome.Terminal.Legacy.Settings theme-variant 'dark'
        gsettings set org.gnome.desktop.interface icon-theme 'ecos'
        gsettings set org.gnome.desktop.interface gtk-theme 'WhiteSur-light'
        gsettings set org.gnome.shell.extensions.user-theme name 'WhiteSur-light'
        gsettings set org.gnome.desktop.interface cursor-theme 'Qogir'
    fi

    # WALLPAPER
    if [ ! -f "$ECOS_INITIALIZED" ]; then
        gsettings set org.gnome.desktop.background picture-uri 'file://'$HOME'/.local/share/wallpaper'
    fi

    # GNOME KEYBINDINGS
    gsettings set org.gnome.desktop.wm.keybindings close "['<Super>q']"
    gsettings set org.gnome.desktop.wm.keybindings minimize "['<Super>h']"
    gsettings set org.gnome.desktop.wm.keybindings show-desktop "['<Super>d']"
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source "[]"
    gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "[]"
    gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['<Super>F11']"

    # Custom Bindings
    # https://askubuntu.com/questions/597395/how-to-set-custom-keyboard-shortcuts-from-terminal
    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/']"

    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'Terminal'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command 'toggle --app gnome-terminal Gnome-terminal'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding '<Super>Return'

    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name 'Firefox'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command 'toggle --app firefox Firefox'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ binding '<Super>b'

    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ name 'Nautilus'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ command 'toggle --app nautilus Org.gnome.Nautilus'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ binding '<Super>e'

    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ name 'KeePass'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ command 'toggle --app keepassxc KeePassXC'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ binding '<Super>k'

    # GNOME EXTENSIONS
    gsettings set org.gnome.shell disable-user-extensions false
    gnome-extensions enable "user-theme@gnome-shell-extensions.gcampax.github.com"
    gnome-extensions enable "x11gestures@joseexposito.github.io"
    gnome-extensions enable "blur-my-shell@aunetx"

    # Extension: Blur My Shell
    gsettings set org.gnome.shell.extensions.blur-my-shell blur-dash false
    gsettings set org.gnome.shell.extensions.blur-my-shell blur-panel false

    # DIRECTORY ICONS
    mkdir -p "$HOME/Projekte"
    gio set -t 'string' "$HOME/Projekte" 'metadata::custom-icon-name' 'folder-favorites'

    # GNOME TERMINAL
    local terminal_profile=$(gsettings get org.gnome.Terminal.ProfilesList default)
    gsettings set org.gnome.Terminal.Legacy.Settings theme-variant 'dark'
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/ scrollbar-policy 'never'
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/ default-size-columns 180
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/ default-size-rows 40
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/ scrollbar-policy 'never'
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/ scroll-on-output true
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$terminal_profile/ palette "['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,209,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']"

    # Terminal Padding
    mkdir -p "$HOME/.config/gtk-3.0"
    echo 'VteTerminal,
TerminalScreen,
vte-terminal {
    padding: 24px 32px 32px 32px;
    -VteTerminal-inner-border: 12px 12px 12px 12px;
}' >"$HOME/.config/gtk-3.0/gtk.css"

    # CLEAR PACMAN
    sudo pacman --noconfirm -Rs $(pacman -Qtdq)
}

# UPDATE
update() {
    echo "Nothing to do..."
}

# REMOVE
remove() {
    sudo systemctl disable gdm.service
}

# ARGUMENTS
if [ "$1" = "--update" ]; then
    update
    exit $?
fi

if [ "$1" = "--remove" ]; then
    remove
    exit $?
fi

if [ "$1" = "--install" ]; then
    install "$@"
    exit $?
fi

# HELP
echo "USE WITH PARAMETERS"
echo "--install"
echo "--update"
echo "--remove"
