#!/bin/sh

# ECOS
export ECOS_HOME="$HOME/.ecos"
export ECOS_CORE="$ECOS_HOME/bin/ecos"
export PATH="$PATH:$ECOS_HOME/bin"

# PATH
export PATH="$PATH:$HOME/.local/bin"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Autostart
# TODO: CREATE DESKTOP FILE
#(sleep 5 && $ECOS_CORE --autostart) &
